version: '3.9'

services:
  db-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'socialmedia'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

# Names our volume
volumes:
  my-db:
