version: '3.9'

services:
  db-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'socialmedia'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  kong:
    image: kong:latest
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml

# Names our volume
volumes:
  my-db: