DEMO_USERS = [
    {
        'email': 'user1@example.com',
        'username': 'user1',
        'accountname': 'user1',
        'avatar_url': 'https://github.com/user1.png',
    },
    {
        'email': 'user2@example.com',
        'username': 'user2',
        'accountname': 'user2',
        'avatar_url': 'https://github.com/user2.png',
    },
    {
        'email': 'user3@example.com',
        'username': 'user3',
        'accountname': 'user3',
        'avatar_url': 'https://github.com/user3.png',
    },
    {
        'email': 'user4@example.com',
        'username': 'user4',
        'accountname': 'user4',
        'avatar_url': 'https://github.com/user4.png',
    },
    {
        'email': 'user5@example.com',
        'username': 'user5',
        'accountname': 'user5',
        'avatar_url': 'https://github.com/user5.png',
    },
    {
        'email': 'user6@example.com',
        'username': 'user6',
        'accountname': 'user6',
        'avatar_url': 'https://github.com/user6.png',
    },
    {
        'email': 'user7@example.com',
        'username': 'user7',
        'accountname': 'user7',
        'avatar_url': 'https://github.com/user7.png',
    },
    {
        'email': 'user8@example.com',
        'username': 'user8',
        'accountname': 'user8',
        'avatar_url': 'https://github.com/user8.png',
    },
    {
        'email': 'user9@example.com',
        'username': 'user9',
        'accountname': 'user9',
        'avatar_url': 'https://github.com/user9.png',
    },
    {
        'email': 'user10@example.com',
        'username': 'user10',
        'accountname': 'user10',
        'avatar_url': 'https://github.com/user10.png',
    },
]


DEMO_POSTS = [
    {'user_email': 'user1@example.com', 'content': 'Primer post de prueba del usuario 1.'},
    {'user_email': 'user1@example.com', 'content': 'Probando que el feed carga correctamente.'},
    {'user_email': 'user1@example.com', 'content': 'Otro mensaje sencillo para llenar el timeline.'},
    {'user_email': 'user2@example.com', 'content': 'Hola desde la cuenta de demostración 2.'},
    {'user_email': 'user2@example.com', 'content': 'Este es un contenido de ejemplo.'},
    {'user_email': 'user2@example.com', 'content': 'Comprobando la segunda cuenta demo.'},
    {'user_email': 'user3@example.com', 'content': 'Publicación rápida del usuario 3.'},
    {'user_email': 'user3@example.com', 'content': 'El backend ha cargado este mensaje.'},
    {'user_email': 'user3@example.com', 'content': 'Un post más para probar el scroll.'},
    {'user_email': 'user4@example.com', 'content': 'Contenido de prueba número diez.'},
    {'user_email': 'user4@example.com', 'content': 'Revisando cómo se muestran los autores.'},
    {'user_email': 'user4@example.com', 'content': 'Mensaje generado para la base de datos demo.'},
    {'user_email': 'user5@example.com', 'content': 'El usuario 5 también tiene publicaciones.'},
    {'user_email': 'user5@example.com', 'content': 'Probando botones, comentarios y likes.'},
    {'user_email': 'user5@example.com', 'content': 'Texto corto para comprobar la interfaz.'},
    {'user_email': 'user6@example.com', 'content': 'Publicación de muestra del usuario 6.'},
    {'user_email': 'user6@example.com', 'content': 'Hoy toca revisar el funcionamiento del feed.'},
    {'user_email': 'user6@example.com', 'content': 'Este mensaje no necesita tener mucho sentido.'},
    {'user_email': 'user7@example.com', 'content': 'Otro usuario participando en la prueba.'},
    {'user_email': 'user7@example.com', 'content': 'Comprobación visual de una publicación.'},
    {'user_email': 'user7@example.com', 'content': 'Más contenido para que la página no esté vacía.'},
    {'user_email': 'user8@example.com', 'content': 'Mensaje de demostración del usuario 8.'},
    {'user_email': 'user8@example.com', 'content': 'Probando la carga de datos iniciales.'},
    {'user_email': 'user8@example.com', 'content': 'Un contenido adicional para el timeline.'},
    {'user_email': 'user9@example.com', 'content': 'El usuario 9 publica su primer mensaje.'},
    {'user_email': 'user9@example.com', 'content': 'Segundo mensaje sencillo de esta cuenta.'},
    {'user_email': 'user9@example.com', 'content': 'Tercera publicación para completar la prueba.'},
    {'user_email': 'user10@example.com', 'content': 'Último usuario de la lista de demostración.'},
    {'user_email': 'user10@example.com', 'content': 'La aplicación ya tiene suficientes posts.'},
    {'user_email': 'user10@example.com', 'content': 'Publicación número treinta de los datos demo.'},
]
